### ISSUE TITLE
Please Add a readme in ClearScreen dir

### ISSUE THREAD

**Issue by Bhupesh-V** [Animesh-Ghosh/Stuff#7]
The README may contain instructions on how to include and compile the header 
For example

Here are complete steps to test **ClearScreen** on any Debian Based System:
1. Make a file **test.c**
```
#include<stdio.h>
#include"clearscreen.h"
int main(){
    printf("Hello");
    ClearScreen();
    printf("\nBitch It works\n");
}
```

2. Download and install the libncurses5-dev:
```sudo apt-get install libncurses5-dev```

3. Compile using ```-lncurses``` flag
```gcc test.c clearscreen.c -lncurses -o test```

**Comment by ghost** [comment]
4.Can also compile using `-lterminfo` flag 
`gcc test.c clearscreen.c -lterminfo -o test`

**Comment by Animesh-Ghosh** [comment]
@Gobtotem and @Bhupesh-V please collaborate and write a README.txt for ClearScreen header directory. Use the link that I put in the source code to refer to how to do it. Also, if the buffer issue persists @Gobtotem please fix it by making different versions for C and C++, if possible. Also mention in the README that all the source code has been copied from that link and it's only the header file that we made cross platform.

**Comment by Bhupesh-V** [comment]
I will make a sample PR in the ```ClearScreen``` directory @Gobtotem you may change accordingly

**Comment by Animesh-Ghosh** [comment]
README.md pushed to master in # 1f9d240. Closing issue. Thanks for all the help! 😄
